# Rarity Configuration
rarity-colors:
  elite: blue
  ultimate: yellow
  legendary: gold
  godly: light_purple
  heroic: red
  executive: black
  pickaxe: white

# Enchant Configuration
enchants:
  position: "lore" # Options: name, lore
  roman-numerals: true # Options: true, false