<?php

namespace Emporium\Prison\Entity;

use pocketmine\block\Block;
use pocketmine\entity\Location;
use pocketmine\entity\object\FallingBlock;
use pocketmine\nbt\tag\CompoundTag;

class FallingBlockEntity extends FallingBlock
{
    public function __construct(Location $location, Block $block, ?CompoundTag $nbt = null)
    {
        parent::__construct($location, $block, $nbt);
    }

    public function updateMovement(bool $teleport = false): void
    {
        if ($this->ticksLived >= 260) $this->flagForDespawn();
        parent::updateMovement($teleport); // TODO: Change the autogenerated stub
    }

    public function onHitGround(): ?float
    {
        $this->flagForDespawn();
        return null;
    }
}